### PR TITLE
Black to 79 chars

### PR DESCRIPTION
**Pull request by folix-01**

### CODE REVIEW

**Comment by folix-01** [comment]
Precepts of PEP-8 \_(-_-)_/

**Comment by cekk** [comment]
i don't really like this approach because 79 chars are too few..now we have bigger screens and we follow black rules.

Also restapi don't use this convention: https://github.com/plone/plone.restapi/blob/master/.flake8

**Comment by folix-01** [comment]
> i don't really like this approach because 79 chars are too few..now we have bigger screens and we follow black rules.
> 
> Also restapi don't use this convention: https://github.com/plone/plone.restapi/blob/master/.flake8

[click](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBISFRIRERISEhgREhISEhISEhISERIRGBgZGRgYGBkcIy4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QGhISHDEhGiE0MTQxNDQxNDE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQxNDQ0NDQ0NjQ0NDQ0MTQxNDQ0NP/AABEIARQAtgMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAAAQIEBQYDB//EAEIQAAIBAgMDBwoDBwMFAQAAAAECAAMRBAUhEjFBBhMiUWFxkRUyUlNUgZOhsdFCcsEUFjNDgtLhI2KSJGODsvEH/8QAGgEAAgMBAQAAAAAAAAAAAAAAAAECAwQFBv/EADERAAICAQIEAwYFBQAAAAAAAAABAhEDBCESMUFRFCIyBRMVM1JxFkJhkeEjodHw8f/aAAwDAQACEQMRAD8A8n8r4r2mv8ap94eV8V7TX+NU+8hCJACd5XxXtNf41T7xfK+K9pr/ABqn3kCEaAn+V8V7TX+NU+8UZvivaa/xqn3lfFEKAneVsT7TX+NU+8Xytifaa/xqn3kOJJUJk4Zrifaa/wAap95qeSuZVa2zRetVLBt/OVCxUnvmKEveRlzjcMB6zXtFjBxTVEoT4XZ7DSyhABd6x76r/ecmXDB+b51tv0eee/1lsym1h1b55lU5M4z9pvZv4m1zl+js3ve8lixQknYsmaaextcTgVsbPUGnCq/3mPxdao6unO1VOoUipUBBHaDN5UTSx6pgsQmzVqX4OfrKMnl3RqwvjtSMg+PxKkqa+IBBsf8AWqfeJ5SxHtFf41T+6WHKHB7LCqo0fRuxpSiXxdqzJNOMqZK8pYj2iv8AGqf3RfKOI9or/Gq/3SLEjIkryjiPaMR8ap/dF8o4j2iv8ap/dIsIDRIOZYj2iv8AGqf3RDmWI9or/Gqf3SOY0xUMkHMsR7RX+NU+8JEMJACIIkURJEYQhFjQCRRJGGwVWp/Dpu/5VJkqpkeKUbTUKgH5YWFECJHMpBsQQRwOhiCSExyqToAT2AEz0v8A/P8AkotqeOqGorqzbNMrsrbdc3F5U8iMYtNHK0mdwxJIUajgA1pq35T4kiwwlQd9S30ETdEkjYPiFG+wjDik9ITENn+J44bxqPGfvFiRuwy++pUgrCjatVU8V8Zmc8yxelVQMWLC4GoldU5QYlhphR7qjyG+aYu9/wBmb+lm+0TVk4ScHaYtTDh0am4ttDiNx4GYjEUWpsyMLFTabhce7iz0npkW1bjKPlNh77FUcei3fwkcflfCTzLjjxooIQhLzKEIQiGhpiGKY0wASJFhIUMhiJFESRGLNlyW5KioFr4gdE6qm7aHWeyZfLaIerTQ7mdQe6+s9fpPYBFFgABpwAkMk+FUi/Dj4nb6HWlSSmuwiqgGgVQBCpUIEdURALtb9ZDxGLFrDxmY2pFfjsJRq3FSmjdtrN4yuwvJGgaiuCxQHVDqCe/qnbG4vZIljlWMUgay6DkuuxTlhGuW5qstCUE2adOmotoAoEj456jm5+USnihbfD9pWXIylbUwbN1zk2Vt2zQUq1PiRJK4ql2SRAybZcw641dtOJmorVqR4ynxpTgbx2FEJ622LNvlNm+F26VQAbl2vDWWFRxeMBDaHiLeMOZJNqzzmLOuJp7Duh/CxHgZxMmUixDFvEMQ0IYwxxjTAAiRIsiMiCJFiSAyVl1TYq039F1J8Z62tZUF+sC08aE22UZxziKjNZ0Fjc+cBxleWNo06aSUmmaWti7yBWr3kVq8rcdjCqsyi9tCeAvKowbZulOMVYmaVWd9hAWtpoL6y4yLK6xALhkHaDM3g82anqq3P6zRYfHVXQPt203WYzZHTza2RzcmojfM1qYJaa61Ax6hvnFio3KT/UJjMTmNdRe+17j95EXNcQxsLX7jLFpsnYpeeHc3gxNv5RP9cX9s/wCwfiTC/tWLPD5f5jg+MPD6feS8Pk7EffQ7m2bEk/ybf+ScXYt/L2f6pjmfF8QPEfeMavieNvEfeHh59g99A1rYW/ED3iMNDZ3G/daY05lVGht8/vBcyqdQ8TDw+TsNZYdzpyjwjis7qjFXAa4BIvbX5ynItvFpoaGZvuKg+8x2d1gaQ2kUM5AVhYnTU8IPHOPNbC4ovkzNGBiRTKxoaY0xxjTAY2LCEiMiRIskYLCPWdadMFmc2A/U9kgHMjTqitvAbvAM9Gyzkth6Kg1AKr21LeaD2CS8SqqLKqqBuCgCVvKk6NEdPJq+R5oMZVXTbYdh/wAy8r19uii7NmezvbdYebO+b4dKmjCx4MN8u8kyGlXph3L9HoAKbDTjLFqMWKPvcnIryYsnpW5k6eHPVLGhtIthUdb8Ba02KcmMMODnvadV5O4b1ZP9Rj+OaZdH+xnehzPnRg6pqHe5PeZy5puv5z0QZDhfVDxb7xRkeG9Uvzkfj+n6Rf8AYa9n5e6PO+ab0h4w5lvSHjPRhkuG9UnzjhlGG9SnhF+IMH0Mfw7J9SPN+aPpDxjTQPWPGel+SMP6pPCIcow/qU8IvxBh+iQ/h2T6keZmieseMfQJQ3sp77T0dskwx30V+cYchwp/kr4t94/xBg+lh8Pyd0YWpUDW2F2T1i0c+EqVEKklrdJbjcRNt+7+F4UwO4tGYnK6VNC1MEEdsnD2zp80lCnuQ8FkxritHl5jTOmJ89/zt9TOZljRIQxhjjGmIYkWIYRDIs3fIDCKq1K7C5Y7CnqUb5hJ6DyJrA0Nkb1dtod+spy3w7FuFJzNS5kSsvXOr1La74r4V3XnCbX4dUyUdHkUOZ4IFSw4S35KfwT+cxppHzW3dclZHhObR14FyR3GU6uf9CUWVuHmTLOLEhOIWCxIQiAWESEACEIQFQsIkIDCRcy/ht7pKkbH+Y006P58PuV5fRI8jxPn1Pzt9TORnfGiz1B1O31M4T1r5s5a5DTGmOMQyIxkWJCRGRpc8m8y5iqLnov0W7DwMpYokWrVDTp2evDpAMN2nzlnzwVLTF8ks2DoaVQ3ZLWvvKy6xGKv+kySjwujp43xpMlGuB2yXgK21cdesoDWk/J6l3Av+EmZdTFPEy1ovYQhOIyAhdfSHiIBxa9xbruLTdZdWKYQOBcpRqMAdxI2jb5ThmarUXB4jZCu1fCm4ttbLMpKk8Ru8J1X7MVJqe+3T+TL4jfkYvnF9JfERS6+kPETf5zmn7Mqtsbe0SLbWxbS/UZy5Nv/ANOG/wB1Y2/rYw+Hw957tZPNVvbpt+v6h4h8PFw7GFDA7iD3G8UfTf2TV5uy18GMQyqH2VZSNSpLAEA9W/T7SxxbDCrh6dFFCvXp0iP9rXue06bzCPs3zO5+Wk+W+9/rtyB6jbluYMG+o1hNFyww6q9N1ADOHD202tnZsT29Ii/d1TOzBnxPDkcG7r/Fl+OXFGwkfHeY0kSPjfMbuktL86H3QsvoZ5Jj/wCJU/O31nAyTmItVqfnb6yLPXPmcoaYhimNMiSEhCEiBFiidKNJnYIqlmJsANSTNJQ5F4hlDMyJf8JuSO+RbS5klFvkZ3D4hqbB1NiJpMNyjV7CoCp3XGolbjuTtekCbBwOKnXwlRuiajJbk4znjexu3r2F9+nylzydpnnGbW3NqfGZPk/V5xGRtSh39andNzkaW2/y0x8pj1UVHBM2e9cnF9y3hCE84y43GXsowYZxtKtGoWXQhlG1ddesaSoxGdCu+HprT2FXEUDvBOjqAAALAawpZ3SXDHDkPtGlUS9l2LttAa3vbXqlHhqgV6bm9lqU3Nt9gwY27bCdrUaunjjCScXXF16r9jHDF6m1v0NxnWYLQVWamKm0SACQLaXvqDOPJfTCpfgav/u0iYjlBhKgAqUWqAG4D06TAHrF2kfLc+o0qZp7L+dVICqmyFZiwHnaWBGk0+IxPMm8seGnta6tXvf6FfBLgrhd/wDSNmGdrVpChRpCkpCjhZQCCAFAtbQTRYuoMOuHQLthqtKgCzEsoIIDXN7kWmBAIAG4gDXqM1Jz3D1lp8+rhqbpUAXVdtb2IN9RruMyaTWcfG8slGW1Xsq/2y3LiquFWjlyww4DU6gLXYMCCxKjZ2bbIPm7ze3/ANzktc9zUYhk2FKqm1ba85ibakDcNNO+VUw6ycJ55Shuv4LsKagkwkfHeY/dJEiYusLFezWR0yfvVXQnJcSaMHymy1i/OIpO151hfXrmcdSDYgg9RBBnqK1LSuzfBU8QjDZAcAlWAAN+qemWdN7oyS0rStHnhjTOtVCpKsCCDYgzk0tMokIhiRDN5yIypUpjEMAXfzb/AIU7O+atzwlLyerA4eiRu2APDfLR6omTI7kb8SqKobWoK2hmazbkjTqXekdhur8JM0O3HU6VR9U4dtpGMmuRbOEZKpGTyXJKmG5xqpXpAAKtzx3zScnKm0avYVHykt8O50qJbtvGYLBCi5dD0X0YHg3AyOpbnimurK/dqNVyRawhCecLghCEACEIQAIQhAVhCEIANqPsgnqEpw9wSeMm5rW2Ut6RtKUVeiZ09DCk5EkdXqASOah1PUJHepOdSppOkkxSfYjZll64hdpdHUaH0uwzIVFKkqwsQbEHgZucI3Gc84yhK6l0AVwN/Buwy7Hk6SMmbDfmRhzEj6iFSQwsQbEdsJeZDScjcx87Dsetk/UTVFzPK6NVkYMpsVNwRwM3mTZuMQtjYOo6S9faJTkhe5qwZPysuQ8kYbEFD3yuJ907pWFrGUmvYsq+O7ZBxeL6D9xkKvVlRmmN6OwDq30lmODnJIhklGEG2ark/m610CMemo1HpDdcS4nlWHrMhDKxUjcRoZsMn5To4CV+i27b/C3f1TJ7Q9kTg3kwq49UY9PrU/LPZmmhGI4YXUgg7iDcR15wmqdM6H2CEIRDCEIQAIsaxtqdAN5MoM45TU6QK0/9R92nmA9pl+DT5M8qxqyueWMFcmdeUVQLzYJFyTZeJ0lNt6GZfFZhUqVBVqOWN/cB1ATQYertL3zvR0b08VFuyvDnWS6B77x7wZxuTvnZRDY1krotO9HQTvt2kcGLtSIcjM8pKdqu36ag+8b4sdylN6iDqT6mJNcXsc2a8zM/JGDxb0mDobEeBHUZGiwInolLF86iVEGjDwPETiFa97mUvJLGEM1AnRgWUH0hvt7po3TslE9mdDDPiiR2J6zKvNaf8M9YMtisg5yNKfcfrNOj3mZtc6xoqgNIoMdwjROwcayXhMxq0vMqMvZe6+Eu8NyuqCwqU1frI0MzMJmzaLBm9cEy2GfJD0s29PlbRPnI48DO371Yb/f/AMZgoXmF+xNI3dP9zQtfmXU3FTlZRG5ah8BK/E8r3OlOmq9rG5mXMSWY/Y+kh+W/uyMtbml1JuNzavVvtu1j+EHZX5SvaPInNpvhjhBVFUihycnucqiywyrFabBOo3dokUCcyhGo0lOfFxIuwZeCRo0eP25UYCuxHS1lis5Eo0zsRnaskK8UPecQJ1RZCiTZRcqKVij9YI98JM5TWNOn+f8AQwmmL2Mc15mZGJFiRlJIweINJ1qLvVge/rE9D51XVXXc6hh3HWeaCbXkrjQ9Pmm86nu7UP2lc42i/BKpV3JlVzuAkTN1OxSv1H6y2anaVueDo0u4y7Q/MFr3/TKjhGR/CMtOwcZBCEIDCEIQAIQhAAjWEdEgA1JKWjtKZGWWuBW6kSL5DXMh4WnaWdMSLRGpHUZKUzh5fWzv4t4I6gRwM5gzoDYFjuUXMrJvYzvKTEbTrT9AXPeYsqsZVLszn8TE/b5QmhKkc6TuTZFgYQMAEk7KcaaNRXG4GzDrU75BixAepXDAMpuGFwesGVXKAdGl3GRuSWPDoaDHpJql+K9XukzlEvRpdxlukjWUerneGykWNZY8RH3TrnJXM4whCImEIQgAQhCABCEIAIBLbK9ZWAS0yvqiYLmPqUekeu8cL8R7xJGIp9M20MZrxHhOFl9bPQYfRERBIWfYjYpbAOrm3u4yxSZPOcUalRupLqvdFjW9kc8qjRXxY0wlxkOUDCEQhIsSLEBIweJak6uu9TfvHETYZnixVSk6iwZL26rzDzTYNiaFO/C4HdNelXnZRqH5BYwx8aZ0TAjjCBhEToIQhAYQhCABCEIAdFEsMt3yvWWGCNrQfIS5lpifO9wnITrid4/KJw2gLk7hqe6cDN8xnoMPy4nLMsTzdNm47l7zMYxvrLLOMw51rL5q7u09crWlkVSM2SXFIaYRDCOis5QhCACRYkWIAmmwTXoU7dbfIzNTUZcAcKh4rUfwM1aV+co1C8gTmZ0iGdJnOODxs6MJziLUEIQgMIQhAAhCEAOiydgxu75BQSxwA1HYYPkJcybmFdKZ6TAdEcdZm8xzQ1Oimi8TxMOUB/137l+kqzOROK42zqLI3BJcgMaYpjSZEQ0wgYQA5whAxAJFiRYgFmpygf8AS/8AkaZSafI6gag6XsVe/uM06bbIinP8tnQiNYR50iM06tHNOULTrCFIdnHYibM7RDALOezACOMSFDsS0UiBiXioY4NJ+XDW8rhLLLmA36SLWw1zKbP/AOO/cv0lYZPzqqHrVCu7QeEgGcnJ6mdKPIaYwxzRpkCQ2EIQAZCTfJVf1bfKJ5Kr+rb5SIEKLJnkqv6tvlF8lV/Vt8oAQpqeS+XrWp1Qrqr7YsrGxK2+8ovJdf1bfKPTL8QDcI4I3EGxHvBk4z4Xa5iaTVM1NXk/il3AN3GRny/FLvpMe4XkHD43MksFarYcDst9ZPTP8zG9A35kW/yM0LVTRU8EGcDRqjfSf/iYyz8abeBlkvKbMOOHQ+636x37y4zjhV8ZNax9iD00Sru3oN4GG0fQbwlt+82L9jXx/wARDyjxXsa+P+I/GPsLwq7lVdvQbwMDterfwMsf3hxnDCqPnGnP8b7Mnh/mHjH2BaaPcr9ipwpv4GKMPWO6m3gZLfO8ef5IH9P+ZGqZlmDfhK9yL+si9XLsSWnidqWV4hvwhe8gSXTyYr0q1VUA362lK9fHtvNX3FR9JEfC4lvOSo35jf8AWVvUzfUmsMEdM4NPnX5o7S6a9Z4yDO5wFf1bfL7xPJ9f1bfL7yluyyiMY0yUcur+rb5QXLMQTYUnJ6gATI2MhwkrybX9W3y+8IWBsoQhEAQhCABCEIAEIQgAQhCABCEIAEIQgAQhCABCEIAW2SYtkFRQqEMy32lvwMntmjlWBSn0dr8Jub3vc3uYQgBww+bvza9CmLqTopHhY6DU6DSSPKrgKQlME7WoUgjXsOvvvFhACrzrGtUpqrBdHJuFsdBoO7UwhCAH/9k=)

**Comment by folix-01** [comment]
> i don't really like this approach because 79 chars are too few..now we have bigger screens and we follow black rules.
> 
> Also restapi don't use this convention: https://github.com/plone/plone.restapi/blob/master/.flake8

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBISFRIRERISEhgREhISEhISEhISERIRGBgZGRgYGBkcIy4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QGhISHDEhGiE0MTQxNDQxNDE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQxNDQ0NDQ0NjQ0NDQ0MTQxNDQ0NP/AABEIARQAtgMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAAAQIEBQYDB//EAEIQAAIBAgMDBwoDBwMFAQAAAAECAAMRBAUhEjFBBhMiUWFxkRUyUlNUgZOhsdFCcsEUFjNDgtLhI2KSJGODsvEH/8QAGgEAAgMBAQAAAAAAAAAAAAAAAAECAwQFBv/EADERAAICAQIEAwYFBQAAAAAAAAABAhEDBCESMUFRFCIyBRMVM1JxFkJhkeEjodHw8f/aAAwDAQACEQMRAD8A8n8r4r2mv8ap94eV8V7TX+NU+8hCJACd5XxXtNf41T7xfK+K9pr/ABqn3kCEaAn+V8V7TX+NU+8UZvivaa/xqn3lfFEKAneVsT7TX+NU+8Xytifaa/xqn3kOJJUJk4Zrifaa/wAap95qeSuZVa2zRetVLBt/OVCxUnvmKEveRlzjcMB6zXtFjBxTVEoT4XZ7DSyhABd6x76r/ecmXDB+b51tv0eee/1lsym1h1b55lU5M4z9pvZv4m1zl+js3ve8lixQknYsmaaextcTgVsbPUGnCq/3mPxdao6unO1VOoUipUBBHaDN5UTSx6pgsQmzVqX4OfrKMnl3RqwvjtSMg+PxKkqa+IBBsf8AWqfeJ5SxHtFf41T+6WHKHB7LCqo0fRuxpSiXxdqzJNOMqZK8pYj2iv8AGqf3RfKOI9or/Gq/3SLEjIkryjiPaMR8ap/dF8o4j2iv8ap/dIsIDRIOZYj2iv8AGqf3RDmWI9or/Gqf3SOY0xUMkHMsR7RX+NU+8JEMJACIIkURJEYQhFjQCRRJGGwVWp/Dpu/5VJkqpkeKUbTUKgH5YWFECJHMpBsQQRwOhiCSExyqToAT2AEz0v8A/P8AkotqeOqGorqzbNMrsrbdc3F5U8iMYtNHK0mdwxJIUajgA1pq35T4kiwwlQd9S30ETdEkjYPiFG+wjDik9ITENn+J44bxqPGfvFiRuwy++pUgrCjatVU8V8Zmc8yxelVQMWLC4GoldU5QYlhphR7qjyG+aYu9/wBmb+lm+0TVk4ScHaYtTDh0am4ttDiNx4GYjEUWpsyMLFTabhce7iz0npkW1bjKPlNh77FUcei3fwkcflfCTzLjjxooIQhLzKEIQiGhpiGKY0wASJFhIUMhiJFESRGLNlyW5KioFr4gdE6qm7aHWeyZfLaIerTQ7mdQe6+s9fpPYBFFgABpwAkMk+FUi/Dj4nb6HWlSSmuwiqgGgVQBCpUIEdURALtb9ZDxGLFrDxmY2pFfjsJRq3FSmjdtrN4yuwvJGgaiuCxQHVDqCe/qnbG4vZIljlWMUgay6DkuuxTlhGuW5qstCUE2adOmotoAoEj456jm5+USnihbfD9pWXIylbUwbN1zk2Vt2zQUq1PiRJK4ql2SRAybZcw641dtOJmorVqR4ynxpTgbx2FEJ622LNvlNm+F26VQAbl2vDWWFRxeMBDaHiLeMOZJNqzzmLOuJp7Duh/CxHgZxMmUixDFvEMQ0IYwxxjTAAiRIsiMiCJFiSAyVl1TYq039F1J8Z62tZUF+sC08aE22UZxziKjNZ0Fjc+cBxleWNo06aSUmmaWti7yBWr3kVq8rcdjCqsyi9tCeAvKowbZulOMVYmaVWd9hAWtpoL6y4yLK6xALhkHaDM3g82anqq3P6zRYfHVXQPt203WYzZHTza2RzcmojfM1qYJaa61Ax6hvnFio3KT/UJjMTmNdRe+17j95EXNcQxsLX7jLFpsnYpeeHc3gxNv5RP9cX9s/wCwfiTC/tWLPD5f5jg+MPD6feS8Pk7EffQ7m2bEk/ybf+ScXYt/L2f6pjmfF8QPEfeMavieNvEfeHh59g99A1rYW/ED3iMNDZ3G/daY05lVGht8/vBcyqdQ8TDw+TsNZYdzpyjwjis7qjFXAa4BIvbX5ynItvFpoaGZvuKg+8x2d1gaQ2kUM5AVhYnTU8IPHOPNbC4ovkzNGBiRTKxoaY0xxjTAY2LCEiMiRIskYLCPWdadMFmc2A/U9kgHMjTqitvAbvAM9Gyzkth6Kg1AKr21LeaD2CS8SqqLKqqBuCgCVvKk6NEdPJq+R5oMZVXTbYdh/wAy8r19uii7NmezvbdYebO+b4dKmjCx4MN8u8kyGlXph3L9HoAKbDTjLFqMWKPvcnIryYsnpW5k6eHPVLGhtIthUdb8Ba02KcmMMODnvadV5O4b1ZP9Rj+OaZdH+xnehzPnRg6pqHe5PeZy5puv5z0QZDhfVDxb7xRkeG9Uvzkfj+n6Rf8AYa9n5e6PO+ab0h4w5lvSHjPRhkuG9UnzjhlGG9SnhF+IMH0Mfw7J9SPN+aPpDxjTQPWPGel+SMP6pPCIcow/qU8IvxBh+iQ/h2T6keZmieseMfQJQ3sp77T0dskwx30V+cYchwp/kr4t94/xBg+lh8Pyd0YWpUDW2F2T1i0c+EqVEKklrdJbjcRNt+7+F4UwO4tGYnK6VNC1MEEdsnD2zp80lCnuQ8FkxritHl5jTOmJ89/zt9TOZljRIQxhjjGmIYkWIYRDIs3fIDCKq1K7C5Y7CnqUb5hJ6DyJrA0Nkb1dtod+spy3w7FuFJzNS5kSsvXOr1La74r4V3XnCbX4dUyUdHkUOZ4IFSw4S35KfwT+cxppHzW3dclZHhObR14FyR3GU6uf9CUWVuHmTLOLEhOIWCxIQiAWESEACEIQFQsIkIDCRcy/ht7pKkbH+Y006P58PuV5fRI8jxPn1Pzt9TORnfGiz1B1O31M4T1r5s5a5DTGmOMQyIxkWJCRGRpc8m8y5iqLnov0W7DwMpYokWrVDTp2evDpAMN2nzlnzwVLTF8ks2DoaVQ3ZLWvvKy6xGKv+kySjwujp43xpMlGuB2yXgK21cdesoDWk/J6l3Av+EmZdTFPEy1ovYQhOIyAhdfSHiIBxa9xbruLTdZdWKYQOBcpRqMAdxI2jb5ThmarUXB4jZCu1fCm4ttbLMpKk8Ru8J1X7MVJqe+3T+TL4jfkYvnF9JfERS6+kPETf5zmn7Mqtsbe0SLbWxbS/UZy5Nv/ANOG/wB1Y2/rYw+Hw957tZPNVvbpt+v6h4h8PFw7GFDA7iD3G8UfTf2TV5uy18GMQyqH2VZSNSpLAEA9W/T7SxxbDCrh6dFFCvXp0iP9rXue06bzCPs3zO5+Wk+W+9/rtyB6jbluYMG+o1hNFyww6q9N1ADOHD202tnZsT29Ii/d1TOzBnxPDkcG7r/Fl+OXFGwkfHeY0kSPjfMbuktL86H3QsvoZ5Jj/wCJU/O31nAyTmItVqfnb6yLPXPmcoaYhimNMiSEhCEiBFiidKNJnYIqlmJsANSTNJQ5F4hlDMyJf8JuSO+RbS5klFvkZ3D4hqbB1NiJpMNyjV7CoCp3XGolbjuTtekCbBwOKnXwlRuiajJbk4znjexu3r2F9+nylzydpnnGbW3NqfGZPk/V5xGRtSh39andNzkaW2/y0x8pj1UVHBM2e9cnF9y3hCE84y43GXsowYZxtKtGoWXQhlG1ddesaSoxGdCu+HprT2FXEUDvBOjqAAALAawpZ3SXDHDkPtGlUS9l2LttAa3vbXqlHhqgV6bm9lqU3Nt9gwY27bCdrUaunjjCScXXF16r9jHDF6m1v0NxnWYLQVWamKm0SACQLaXvqDOPJfTCpfgav/u0iYjlBhKgAqUWqAG4D06TAHrF2kfLc+o0qZp7L+dVICqmyFZiwHnaWBGk0+IxPMm8seGnta6tXvf6FfBLgrhd/wDSNmGdrVpChRpCkpCjhZQCCAFAtbQTRYuoMOuHQLthqtKgCzEsoIIDXN7kWmBAIAG4gDXqM1Jz3D1lp8+rhqbpUAXVdtb2IN9RruMyaTWcfG8slGW1Xsq/2y3LiquFWjlyww4DU6gLXYMCCxKjZ2bbIPm7ze3/ANzktc9zUYhk2FKqm1ba85ibakDcNNO+VUw6ycJ55Shuv4LsKagkwkfHeY/dJEiYusLFezWR0yfvVXQnJcSaMHymy1i/OIpO151hfXrmcdSDYgg9RBBnqK1LSuzfBU8QjDZAcAlWAAN+qemWdN7oyS0rStHnhjTOtVCpKsCCDYgzk0tMokIhiRDN5yIypUpjEMAXfzb/AIU7O+atzwlLyerA4eiRu2APDfLR6omTI7kb8SqKobWoK2hmazbkjTqXekdhur8JM0O3HU6VR9U4dtpGMmuRbOEZKpGTyXJKmG5xqpXpAAKtzx3zScnKm0avYVHykt8O50qJbtvGYLBCi5dD0X0YHg3AyOpbnimurK/dqNVyRawhCecLghCEACEIQAIQhAVhCEIANqPsgnqEpw9wSeMm5rW2Ut6RtKUVeiZ09DCk5EkdXqASOah1PUJHepOdSppOkkxSfYjZll64hdpdHUaH0uwzIVFKkqwsQbEHgZucI3Gc84yhK6l0AVwN/Buwy7Hk6SMmbDfmRhzEj6iFSQwsQbEdsJeZDScjcx87Dsetk/UTVFzPK6NVkYMpsVNwRwM3mTZuMQtjYOo6S9faJTkhe5qwZPysuQ8kYbEFD3yuJ907pWFrGUmvYsq+O7ZBxeL6D9xkKvVlRmmN6OwDq30lmODnJIhklGEG2ark/m610CMemo1HpDdcS4nlWHrMhDKxUjcRoZsMn5To4CV+i27b/C3f1TJ7Q9kTg3kwq49UY9PrU/LPZmmhGI4YXUgg7iDcR15wmqdM6H2CEIRDCEIQAIsaxtqdAN5MoM45TU6QK0/9R92nmA9pl+DT5M8qxqyueWMFcmdeUVQLzYJFyTZeJ0lNt6GZfFZhUqVBVqOWN/cB1ATQYertL3zvR0b08VFuyvDnWS6B77x7wZxuTvnZRDY1krotO9HQTvt2kcGLtSIcjM8pKdqu36ag+8b4sdylN6iDqT6mJNcXsc2a8zM/JGDxb0mDobEeBHUZGiwInolLF86iVEGjDwPETiFa97mUvJLGEM1AnRgWUH0hvt7po3TslE9mdDDPiiR2J6zKvNaf8M9YMtisg5yNKfcfrNOj3mZtc6xoqgNIoMdwjROwcayXhMxq0vMqMvZe6+Eu8NyuqCwqU1frI0MzMJmzaLBm9cEy2GfJD0s29PlbRPnI48DO371Yb/f/AMZgoXmF+xNI3dP9zQtfmXU3FTlZRG5ah8BK/E8r3OlOmq9rG5mXMSWY/Y+kh+W/uyMtbml1JuNzavVvtu1j+EHZX5SvaPInNpvhjhBVFUihycnucqiywyrFabBOo3dokUCcyhGo0lOfFxIuwZeCRo0eP25UYCuxHS1lis5Eo0zsRnaskK8UPecQJ1RZCiTZRcqKVij9YI98JM5TWNOn+f8AQwmmL2Mc15mZGJFiRlJIweINJ1qLvVge/rE9D51XVXXc6hh3HWeaCbXkrjQ9Pmm86nu7UP2lc42i/BKpV3JlVzuAkTN1OxSv1H6y2anaVueDo0u4y7Q/MFr3/TKjhGR/CMtOwcZBCEIDCEIQAIQhAAjWEdEgA1JKWjtKZGWWuBW6kSL5DXMh4WnaWdMSLRGpHUZKUzh5fWzv4t4I6gRwM5gzoDYFjuUXMrJvYzvKTEbTrT9AXPeYsqsZVLszn8TE/b5QmhKkc6TuTZFgYQMAEk7KcaaNRXG4GzDrU75BixAepXDAMpuGFwesGVXKAdGl3GRuSWPDoaDHpJql+K9XukzlEvRpdxlukjWUerneGykWNZY8RH3TrnJXM4whCImEIQgAQhCABCEIAIBLbK9ZWAS0yvqiYLmPqUekeu8cL8R7xJGIp9M20MZrxHhOFl9bPQYfRERBIWfYjYpbAOrm3u4yxSZPOcUalRupLqvdFjW9kc8qjRXxY0wlxkOUDCEQhIsSLEBIweJak6uu9TfvHETYZnixVSk6iwZL26rzDzTYNiaFO/C4HdNelXnZRqH5BYwx8aZ0TAjjCBhEToIQhAYQhCABCEIAdFEsMt3yvWWGCNrQfIS5lpifO9wnITrid4/KJw2gLk7hqe6cDN8xnoMPy4nLMsTzdNm47l7zMYxvrLLOMw51rL5q7u09crWlkVSM2SXFIaYRDCOis5QhCACRYkWIAmmwTXoU7dbfIzNTUZcAcKh4rUfwM1aV+co1C8gTmZ0iGdJnOODxs6MJziLUEIQgMIQhAAhCEAOiydgxu75BQSxwA1HYYPkJcybmFdKZ6TAdEcdZm8xzQ1Oimi8TxMOUB/137l+kqzOROK42zqLI3BJcgMaYpjSZEQ0wgYQA5whAxAJFiRYgFmpygf8AS/8AkaZSafI6gag6XsVe/uM06bbIinP8tnQiNYR50iM06tHNOULTrCFIdnHYibM7RDALOezACOMSFDsS0UiBiXioY4NJ+XDW8rhLLLmA36SLWw1zKbP/AOO/cv0lYZPzqqHrVCu7QeEgGcnJ6mdKPIaYwxzRpkCQ2EIQAZCTfJVf1bfKJ5Kr+rb5SIEKLJnkqv6tvlF8lV/Vt8oAQpqeS+XrWp1Qrqr7YsrGxK2+8ovJdf1bfKPTL8QDcI4I3EGxHvBk4z4Xa5iaTVM1NXk/il3AN3GRny/FLvpMe4XkHD43MksFarYcDst9ZPTP8zG9A35kW/yM0LVTRU8EGcDRqjfSf/iYyz8abeBlkvKbMOOHQ+636x37y4zjhV8ZNax9iD00Sru3oN4GG0fQbwlt+82L9jXx/wARDyjxXsa+P+I/GPsLwq7lVdvQbwMDterfwMsf3hxnDCqPnGnP8b7Mnh/mHjH2BaaPcr9ipwpv4GKMPWO6m3gZLfO8ef5IH9P+ZGqZlmDfhK9yL+si9XLsSWnidqWV4hvwhe8gSXTyYr0q1VUA362lK9fHtvNX3FR9JEfC4lvOSo35jf8AWVvUzfUmsMEdM4NPnX5o7S6a9Z4yDO5wFf1bfL7xPJ9f1bfL7yluyyiMY0yUcur+rb5QXLMQTYUnJ6gATI2MhwkrybX9W3y+8IWBsoQhEAQhCABCEIAEIQgAQhCABCEIAEIQgAQhCABCEIAW2SYtkFRQqEMy32lvwMntmjlWBSn0dr8Jub3vc3uYQgBww+bvza9CmLqTopHhY6DU6DSSPKrgKQlME7WoUgjXsOvvvFhACrzrGtUpqrBdHJuFsdBoO7UwhCAH/9k=

**Comment by folix-01** [comment]
> i don't really like this approach because 79 chars are too few..now we have bigger screens and we follow black rules.
> 
> Also restapi don't use this convention: https://github.com/plone/plone.restapi/blob/master/.flake8
Screenshot 2023-07-19 at 09 18 14

**Comment by folix-01** [comment]
> i don't really like this approach because 79 chars are too few..now we have bigger screens and we follow black rules.
> 
> Also restapi don't use this convention: https://github.com/plone/plone.restapi/blob/master/.flake8

Also every time I see the github diff view of the PR I just want to close the window

**Pull request closed without merging**
